# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #HostName
  config.vm.hostname = "srv-nv"
  #Boxname
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_url = "http://localhost:8080/ubuntu/xenial64"
  # automatische Updates verweigern
   config.vm.box_check_update = false 
  #Netzwerk
  config.vm.network "public_network", ip: "192.168.55.10"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/var/www/html" 
  #Portforwarding for Apache Web service
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     #Name VirtualBox
     vb.name = "srv-nv"
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     #CPU Core
     vb.cpus = "2"
   end  
  config.vm.provision "shell", inline: <<-SHELL
    #install webserver
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get install -y apache2
    #HTTPS aktivieren 
    sudo a2ensite default-ssl.conf
    sudo a2enmod ssl
    sudo a2dissite 000-default.conf 
    sudo service apache2 restart 
    #Firewall
    sudo apt-get install ufw
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    sudo ufw allow 80/tcp
    sudo ufw allow 443/tcp
    sudo ufw allow 22/tcp
    echo "y" | sudo ufw enable 
    #Standarduser erzeugen
    sudo useradd localadmin
    sudo usermod -aG sudo localadmin
  SHELL
end
 
    
    
  
  
  
  

    